package scanner

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/javimosch/token-optimizer-cli/tokenizer"
)

type FileInfo struct {
	Path     string            `json:"path"`
	Size     int64             `json:"size"`
	Language string            `json:"language"`
	Tokens   tokenizer.FileCount `json:"tokens"`
	Issues   []Issue           `json:"issues,omitempty"`
}

type Issue struct {
	Severity  string `json:"severity"`
	Message   string `json:"message"`
	Suggestion string `json:"suggestion,omitempty"`
}

type ScanResult struct {
	Files        []FileInfo `json:"files"`
	TotalFiles   int        `json:"total_files"`
	TotalTokens  int        `json:"total_tokens"`
	TotalSize    int64      `json:"total_size"`
	BloatFiles   int        `json:"bloat_files"`
	BloatTokens  int        `json:"bloat_tokens"`
}

var skipDirs = map[string]bool{
	".git": true, "node_modules": true, ".next": true,
	"dist": true, "build": true, "target": true,
	"__pycache__": true, ".cache": true, ".venv": true,
	"venv": true, "env": true, ".env": true,
	"vendor": true, ".pytest_cache": true,
}

var skipFiles = map[string]bool{
	"token-optimizer-cli": true,
	"token-optimizer-cli-linux-amd64.tar.gz": true,
	"token-optimizer-cli-linux-amd64.tar.gz.sha256": true,
}

var binaryExts = map[string]bool{
	".png": true, ".jpg": true, ".jpeg": true, ".gif": true,
	".ico": true, ".svg": true, ".woff": true, ".woff2": true,
	".ttf": true, ".eot": true, ".pdf": true, ".zip": true,
	".tar": true, ".gz": true, ".bz2": true, ".7z": true,
	".exe": true, ".bin": true, ".dll": true, ".so": true,
	".dylib": true, ".o": true, ".a": true, ".class": true,
	".pyc": true, ".pyo": true, ".mp3": true, ".mp4": true,
	".mov": true, ".avi": true, ".webm": true,
}

var langMap = map[string]string{
	".go": "Go", ".py": "Python", ".js": "JavaScript",
	".ts": "TypeScript", ".tsx": "TypeScript (React)", ".jsx": "JavaScript (React)",
	".rs": "Rust", ".rb": "Ruby", ".java": "Java",
	".kt": "Kotlin", ".swift": "Swift", ".c": "C",
	".h": "C", ".cpp": "C++", ".hpp": "C++",
	".cs": "C#", ".php": "PHP", ".pl": "Perl",
	".sh": "Shell", ".bash": "Shell", ".zsh": "Shell",
	".md": "Markdown", ".yml": "YAML", ".yaml": "YAML",
	".json": "JSON", ".toml": "TOML", ".xml": "XML",
	".html": "HTML", ".css": "CSS", ".scss": "SCSS",
	".sql": "SQL", ".r": "R", ".m": "MATLAB",
	".lua": "Lua", ".scala": "Scala", ".dart": "Dart",
	".txt": "Text", ".cfg": "Config", ".conf": "Config",
}

func Scan(root string, json bool) (*ScanResult, error) {
	result := &ScanResult{}

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}

		if info.IsDir() {
			if skipDirs[info.Name()] {
				return filepath.SkipDir
			}
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		if binaryExts[ext] || skipFiles[info.Name()] || info.Size() > 10*1024*1024 {
			return nil
		}

		rel, _ := filepath.Rel(root, path)
		if strings.HasPrefix(rel, ".") && rel != ".env.example" {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}

		text := string(data)
		fc := tokenizer.CountFile(text)
		lang := detectLanguage(path, ext)
		fi := FileInfo{
			Path:     rel,
			Size:     info.Size(),
			Language: lang,
			Tokens:   fc,
		}

		if fc.TokenEstimate > 500 {
			fi.Issues = append(fi.Issues, Issue{
				Severity:   "warning",
				Message:    "Large file: ~" + itoa(fc.TokenEstimate) + " tokens",
				Suggestion: "Consider splitting into smaller files or using include patterns",
			})
		}

		if hasLongLines(text) {
			fi.Issues = append(fi.Issues, Issue{
				Severity:   "info",
				Message:    "Contains lines >500 chars",
				Suggestion: "Break long lines for token efficiency",
			})
		}

		if hasBoilerplate(text, ext) {
			fi.Issues = append(fi.Issues, Issue{
				Severity:   "info",
				Message:    "Possible boilerplate or generated code detected",
				Suggestion: "Consider minimizing for context usage",
			})
		}

		result.Files = append(result.Files, fi)
		result.TotalFiles++
		result.TotalTokens += fc.TokenEstimate
		result.TotalSize += info.Size()
		if fc.TokenEstimate > 1000 {
			result.BloatFiles++
			result.BloatTokens += fc.TokenEstimate
		}

		return nil
	})

	return result, err
}

func detectLanguage(path, ext string) string {
	if l, ok := langMap[ext]; ok {
		return l
	}
	if strings.Contains(path, "Dockerfile") {
		return "Dockerfile"
	}
	if strings.Contains(path, "Makefile") {
		return "Makefile"
	}
	return "Unknown"
}

func hasLongLines(text string) bool {
	for _, line := range strings.Split(text, "\n") {
		if len([]rune(strings.TrimRight(line, "\r"))) > 500 {
			return true
		}
	}
	return false
}

func hasBoilerplate(text string, ext string) bool {
	boilerplate := []string{
		"auto-generated", "autogenerated", "do not edit",
		"DO NOT EDIT", "@generated", "This file is generated",
	}
	for _, pattern := range boilerplate {
		if strings.Contains(text, pattern) {
			return true
		}
	}
	return false
}

func CheckSingleFile(path string) (*FileInfo, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, err
	}
	if info.IsDir() {
		return nil, fmt.Errorf("%s is a directory, use scan or audit instead", path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	text := string(data)
	ext := strings.ToLower(filepath.Ext(path))
	fc := tokenizer.CountFile(text)
	fi := &FileInfo{
		Path:     path,
		Size:     info.Size(),
		Language: detectLanguage(path, ext),
		Tokens:   fc,
	}

	if fc.Lines < 2 {
		return fi, nil
	}

	lines := strings.Split(text, "\n")
	blankCount := 0
	longLines := 0
	commentLines := 0
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			blankCount++
		}
		if len([]rune(trimmed)) > 500 {
			longLines++
		}
		if strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "#") ||
			strings.HasPrefix(trimmed, "/*") || strings.HasPrefix(trimmed, "*") {
			commentLines++
		}
	}

	if blankCount > fc.Lines/3 {
		fi.Issues = append(fi.Issues, Issue{
			Severity:    "info",
			Message:     fmt.Sprintf("High blank line density: %d/%d lines", blankCount, fc.Lines),
			Suggestion:  "Consider compressing vertical whitespace",
		})
	}
	if longLines > 0 {
		fi.Issues = append(fi.Issues, Issue{
			Severity:    "warning",
			Message:     fmt.Sprintf("%d lines exceed 500 chars", longLines),
			Suggestion:  "Break long lines for token efficiency",
		})
	}
	if commentLines > fc.Lines/2 && fc.Lines > 20 {
		fi.Issues = append(fi.Issues, Issue{
			Severity:    "info",
			Message:     fmt.Sprintf("High comment density: %d/%d lines", commentLines, fc.Lines),
			Suggestion:  "Trim redundant comments to save tokens",
		})
	}

	return fi, nil
}

func itoa(n int) string {
	return strconv.Itoa(n)
}
